# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb608843b85985f98b7570c04a119c6b90afc993c97db633be6f079c8a0bc5dd20bb0573e03c656e1dd6ef20940cda1599b07daa365f62effb58fecd31f12e6d

test:
  secret_key_base: edb032227b3fd75aa47c5897aae1134c34b28ed7155649c17c7887e6eda283e839f31c6dffd2e9eeccacec50f9435d4ddffc26fc891bad7c3b9820615a848c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
